# Generated by Django 2.2.4 on 2019-08-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('sentiment', models.FloatField()),
            ],
        ),
    ]
